### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [galacticdragon/prj-rev-bwfs-dasmoto#3]
So overall excellent.  In this first project I look for two items.  Did you use divs to organize each section of html and how repetitive is your css.

You did great on both parts.  I know I mention the id issue but classes fixes this and overall the goal was for you to assign everything properly.  Using span for the price usually happens when the learner doesn't know the option didn't exist.

As a challenge take a look at the bootstrap framework at getbootstrap.com  .  See if you can add it to this site and make it mobile friendly.  The concepts in using this will help prepare you for the more complicated projects.

**Comment by galacticdragon** [comment]
Thanks for the feedback! I will take a look at incorporating bootstrap into the site I am building
